# SITE CONFIGURATION
title: Plant Ecology, Forest Ecology & High-Mountain Ecology # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Homepage of the Opgenoorth lab.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Lars Opgenoorth
  links:
    #- https://twitter.com/epidiverse
    #- https://www.gretathunbergsweden/
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    #- https://github.com/benbalter
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'home', link: '/'}
  - {name: 'people', link: '/team'}
  - {name: 'research', link: '/research'}
  - {name: 'publications', link: '/publications'}
  #- {name: 'Teaching', link: '/teaching'}
  - {name: 'funding', link: '/funding'}

tagline: >
  Lars Opgenoorth

hero_img: posts/mountain-forest.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: opgenoorth@uni-marburg.de # email for form submission

twitter_username: EpiDiverse # replace with your_twitter_username or comment to remove link from footer
#github_username: janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
